//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 08:20:52 PM GMT+03:00 
//


package com.sap;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for JaxbNote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JaxbNote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="n" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="d" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="l" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="c" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="p" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="o" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="a" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JaxbNote", namespace = "", propOrder = {
    "content"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class JaxbNote {

    @XmlValue
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String content;
    @XmlAttribute(name = "n", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected int n;
    @XmlAttribute(name = "d", required = true)
    @XmlSchemaType(name = "date")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar d;
    @XmlAttribute(name = "l", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String l;
    @XmlAttribute(name = "c", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String c;
    @XmlAttribute(name = "p", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String p;
    @XmlAttribute(name = "m")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String m;
    @XmlAttribute(name = "o")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String o;
    @XmlAttribute(name = "a", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String a;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the n property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public int getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setN(int value) {
        this.n = value;
    }

    /**
     * Gets the value of the d property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setD(XMLGregorianCalendar value) {
        this.d = value;
    }

    /**
     * Gets the value of the l property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getL() {
        return l;
    }

    /**
     * Sets the value of the l property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setL(String value) {
        this.l = value;
    }

    /**
     * Gets the value of the c property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setC(String value) {
        this.c = value;
    }

    /**
     * Gets the value of the p property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getP() {
        return p;
    }

    /**
     * Sets the value of the p property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setP(String value) {
        this.p = value;
    }

    /**
     * Gets the value of the m property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setM(String value) {
        this.m = value;
    }

    /**
     * Gets the value of the o property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getO() {
        return o;
    }

    /**
     * Sets the value of the o property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setO(String value) {
        this.o = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-01-18T08:20:52+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setA(String value) {
        this.a = value;
    }

}
