//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 08:20:52 PM GMT+03:00 
//


package com.sap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Priority_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Priority");
    private final static QName _Title_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Title");
    private final static QName _Lang_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Lang");
    private final static QName _Text_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Text");
    private final static QName _TypeText_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "TypeText");
    private final static QName _RefTitle_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "RefTitle");
    private final static QName _Type_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Type");
    private final static QName _ReleasedOn_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "ReleasedOn");
    private final static QName _TypeKey_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "TypeKey");
    private final static QName _Id_QNAME = new QName("http://www.w3.org/2005/Atom", "id");
    private final static QName _ComponentText_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "ComponentText");
    private final static QName _RefNum_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "RefNum");
    private final static QName _LangMaster_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "LangMaster");
    private final static QName _RefKey_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "RefKey");
    private final static QName _Favorite_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Favorite");
    private final static QName _Category_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Category");
    private final static QName _LangText_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "LangText");
    private final static QName _ComponentKey_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "ComponentKey");
    private final static QName _SapNotesKey_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "SapNotesKey");
    private final static QName _RefType_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "RefType");
    private final static QName _RefUrl_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "RefUrl");
    private final static QName _Version_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Version");
    private final static QName _Language_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "Language");
    private final static QName _LanguageText_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "LanguageText");
    private final static QName _SapNotesNumber_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "SapNotesNumber");
    private final static QName _CurrentLang_QNAME = new QName("http://schemas.microsoft.com/ado/2007/08/dataservices", "CurrentLang");
    private final static QName _Updated_QNAME = new QName("http://www.w3.org/2005/Atom", "updated");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Inline }
     * 
     */
    public Inline createInline() {
        return new Inline();
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Snotes }
     * 
     */
    public Snotes createSnotes() {
        return new Snotes();
    }

    /**
     * Create an instance of {@link JaxbNote }
     * 
     */
    public JaxbNote createJaxbNote() {
        return new JaxbNote();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Priority")
    public JAXBElement<String> createPriority(String value) {
        return new JAXBElement<String>(_Priority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Lang")
    public JAXBElement<String> createLang(String value) {
        return new JAXBElement<String>(_Lang_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "TypeText")
    public JAXBElement<String> createTypeText(String value) {
        return new JAXBElement<String>(_TypeText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "RefTitle")
    public JAXBElement<String> createRefTitle(String value) {
        return new JAXBElement<String>(_RefTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "ReleasedOn")
    public JAXBElement<String> createReleasedOn(String value) {
        return new JAXBElement<String>(_ReleasedOn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "TypeKey")
    public JAXBElement<String> createTypeKey(String value) {
        return new JAXBElement<String>(_TypeKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "ComponentText")
    public JAXBElement<String> createComponentText(String value) {
        return new JAXBElement<String>(_ComponentText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "RefNum")
    public JAXBElement<String> createRefNum(String value) {
        return new JAXBElement<String>(_RefNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "LangMaster")
    public JAXBElement<String> createLangMaster(String value) {
        return new JAXBElement<String>(_LangMaster_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "RefKey")
    public JAXBElement<String> createRefKey(String value) {
        return new JAXBElement<String>(_RefKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Favorite")
    public JAXBElement<String> createFavorite(String value) {
        return new JAXBElement<String>(_Favorite_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<String>(_Category_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "LangText")
    public JAXBElement<String> createLangText(String value) {
        return new JAXBElement<String>(_LangText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "ComponentKey")
    public JAXBElement<String> createComponentKey(String value) {
        return new JAXBElement<String>(_ComponentKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "SapNotesKey")
    public JAXBElement<String> createSapNotesKey(String value) {
        return new JAXBElement<String>(_SapNotesKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "RefType")
    public JAXBElement<String> createRefType(String value) {
        return new JAXBElement<String>(_RefType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "RefUrl")
    public JAXBElement<String> createRefUrl(String value) {
        return new JAXBElement<String>(_RefUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "LanguageText")
    public JAXBElement<String> createLanguageText(String value) {
        return new JAXBElement<String>(_LanguageText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "SapNotesNumber")
    public JAXBElement<String> createSapNotesNumber(String value) {
        return new JAXBElement<String>(_SapNotesNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2007/08/dataservices", name = "CurrentLang")
    public JAXBElement<String> createCurrentLang(String value) {
        return new JAXBElement<String>(_CurrentLang_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "updated")
    public JAXBElement<XMLGregorianCalendar> createUpdated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Updated_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
